volumes:
  db-data:

services:
  app:
    build:
      context: .
      dockerfile: docker/local/app/Dockerfile
    container_name: app
    ports:
      - 5173:5173
      - 8000:8000
    # この指定がないと WLS2 の Ubuntu に直接 Docker インストールで動かしている場合に PHP がデバッグできない
    # Docker Desktop をインストールしていればなくても動くがあっても問題ない
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/src
      # https://www.php.net/downloads.php?os=windows
      - ./docker/local/app/php.ini:/etc/php.d/php.ini
      - ./logs/npm:/root/.npm/_logs
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/local/postgres/Dockerfile
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: study_laravel
      POSTGRES_PASSWORD: Passw0rd
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - db-data:/var/lib/postgresql
      - ./logs/postgres:/var/log/postgresql/18
